[main]
dpi-aware = yes
font = IBM Plex Mono:size=10
icons-enabled = true
hide-prompt = no
#prompt = "Search |  "
use-bold = false
inner-pad = 0
vertical-pad = 10
horizontal-pad = 10
#minimal-lines = true
icon-theme = Tela-circle-dark
letter-spacing = 1
line-height = 25
width = 50
#lines = 12
lines = 1
image-size-ratio = 0
#exit-on-keyboard-focus-loss=no
#exit-immediately-if-empty=no
#fuzzy-max-distance=0
#exit-on-keyboard-focus-loss = no
#hide-before-typing = yes
[border]
width = 2
radius = 0

[colors]
background = 000000FF
border = 000000FF
text = FFFFFFFF
match = d8dee9FF
placeholder = 9ECE6AFF
selection = 222222FF
selection-text = FFFFFFFF
selection-match = FFFFFFFF

