''[main]
dpi-aware = yes
font = IBM Plex Mono:size=10
icons-enabled = true
hide-prompt = yes
#prompt = "Search..."
use-bold = false
inner-pad = 0
vertical-pad = 10
horizontal-pad = 10
#minimal-lines = true
icon-theme = Tela-circle
letter-spacing = 1
line-height = 25
width = 35
lines = 12
image-size-ratio = 0

[border]
width = 2
radius = 0

[colors]
background = 000000FF
border = 5294e2FF
text = d8dee9FF
match = 5294e2FF
placeholder = 9ECE6AFF
selection = 5294e2FF
selection-text = 000000FF
selection-match = 000000FF

