#! /bin/sh

#Autostart
sxhkd &
#nitrogen --restore &
feh --bg-fill ~/Downloads/Wallpapers/unsplash.jpg &
rofi -show drun -matching prefix -drun-match-fields name -theme ~/.config/rofi/nord.rasi &
picom &
xset dpms 0 0 360 &

#Workspaces
bspc monitor -d 1 2 3

#### BSPWM configuration ####
bspc config border_width                  2
bspc config window_gap                    1
bspc config top_padding                   1
bspc config bottom_padding                1
bspc config left_padding                  1
bspc config right_padding                 1
bspc config single_monocle                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
for side in top right bottom left; do bspc config ${side}_monocle_padding -1; done

#Remove X cursor
xsetroot -cursor_name left_ptr &

#### BSPWM coloring ####
#bspc config normal_border_color               "#4c566a"
#bspc config active_border_color	      	      "#1e1e1e"
bspc config focused_border_color	      "#5294e2"

bspc rule -a Gnome-calculator state=floating center=true


